version: "3.7"

services:

  # Go開発用サービス
  notify-slack-of-amplify-events:
    build:
      context: .
      dockerfile: ./build/Dockerfile
      target: ${APP_ENV}
    container_name: notify-slack-of-amplify-events
    env_file:
      - .docker.env
    image: notify-slack-of-amplify-events:latest
    tty: true
    volumes:
      - .:/go/src

  # Lambda検証用サービス
  lambda:
    build:
      context: .
      dockerfile: ./build/Dockerfile
      target: ${APP_ENV}
    command: /go/bin/cmd
    container_name: lambda
    entrypoint: /aws-lambda/aws-lambda-rie
    env_file:
      - .docker.env
    image: notify-slack-of-amplify-events:latest
    ports:
      - 9000:8080
    volumes:
      - ~/.aws-lambda-rie:/aws-lambda
      - .:/go/src
