version: "3.7"

services:

  go:
    container_name: notify-slack-of-amplify-events
    build:
      dockerfile: ./build/Dockerfile
      context: .
    image: notify-slack-of-amplify-events:latest
    tty: true
    volumes:
      - .:/go/src
    environment:
      TZ: "Asia/Tokyo"
      LANG: "ja_JP.UTF-8"
