version: "3.7"

services:

  notify-slack-of-amplify-events:
    build:
      context: .
      dockerfile: ./build/Dockerfile
      target: ${APP_ENV}
    container_name: notify-slack-of-amplify-events
    env_file:
      - .docker.env
    image: notify-slack-of-amplify-events:latest
    tty: true
    volumes:
      - .:/go/src
