version: "3.7"

services:

  # Go開発用サービス
  app:
    build:
      context: .
      dockerfile: ./build/Dockerfile
      target: ${APP_ENV} # .envファイルから参照．
    container_name: notify-slack-of-amplify-events-app
    env_file:
      - .env
      - .env.docker
    image: notify-slack-of-amplify-events:latest
    networks:
      - default
    tty: true
    volumes:
      - .:/go/src

  # Lambda検証用サービス
  lambda:
    build:
      context: .
      dockerfile: ./build/Dockerfile
      target: ${APP_ENV} # .envファイルから参照．
    command: /go/bin/cmd
    container_name: notify-slack-of-amplify-events-lambda
    entrypoint: /aws-lambda/aws-lambda-rie
    env_file:
      - .env
      - .env.docker
    image: notify-slack-of-amplify-events:latest
    networks:
      - default
    ports:
      - "9000:8080"
    volumes:
      - ~/.aws-lambda-rie:/aws-lambda
      - .:/go/src

networks:
  default:
    name: notify-slack-of-amplify-events-network
