# 変数
# NOTE: 開発環境で静的解析しやすいように，デフォルト値を設定する．
custom:
  appEnv: ${env:APP_ENV, "dev"}
  ecrAccountUrl: ${env:AWS_ECR_ACCOUNT_URL, "dev"}
  ecrImageDigest: ${env:CIRCLE_SHA1, "sha256:dev"}
  service: notify-slack-of-amplify-events

# サービス名
service: ${self:custom.service}

# バージョン
# NOTE: v3以降の実験的機能について（https://www.serverless.com/framework/docs/deprecations/）
frameworkVersion: '2'

# 静的解析ルール．
# NOTE: 開発環境で静的解析しやすいように，ルールを弱める．
configValidationMode: warn
variablesResolutionMode: null

# プロバイダー
provider:
  name: aws
  region: ap-northeast-1
  stackName: ${self:custom.appEnv}-${self:custom.service}-stack
  stage: ${self:custom.appEnv}
  # ECR
  ecr:
    scanOnPush: true
    images:
      baseImage:
        uri: ${self:custom.ecrAccountUrl}/${self:custom.appEnv}-${self:custom.service}-repository@${self:custom.ecrImageDigest}
  lambdaHashingVersion: 20201221

# デプロイ対象のパッケージ
package:
  patterns:
    - ./bin/**

# Lambda
functions:
  main:
    description: The function that notify slack of amplify events
    events:
      - eventBridge:
          pattern: ${file(./serverless_configs/events/amplify_event.json)}
    image: 
      name: baseimage
    maximumRetryAttempts: 1
    memorySize: 512
    name: ${self:custom.appEnv}-${self:custom.service}
    role: !GetAtt LambdaRole.Arn
    runtime: go1.x

# 追加AWSリソース
resources:
  Resources:
    LambdaRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:custom.appEnv}-${self:custom.service}-lambda-role
        Description: The role for ${self:custom.appEnv}-${self:custom.service}-lambda
        AssumeRolePolicyDocument: ${file(./serverless_configs/policies/trust_policies/lambda_policy.json)}
        # インラインポリシー
        Policies:
          - PolicyName: ${self:custom.appEnv}-${self:custom.service}-lambda-execution-policy
            PolicyDocument: ${file(./serverless_configs/policies/custom_managed_policies/lambda_execution_policy.json)}
        # 管理ポリシー
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AWSLambdaExecute
          
