service: notify-slack-of-amplify-events

frameworkVersion: '2'

custom:
  env: dev
  service: notify-slack-of-amplify-events

provider:
  name: aws
  region: ap-northeast-1
  stackName: ${self:custom.env}-${self:custom.service}-stack
  stage: ${self:custom.env}

package:
  patterns:
    - ./bin/**

functions:
  main: 
    description: The function that notify slack of amplify events
    events:
      - eventBridge:
          pattern: ${file(./serverless_configs/events/amplify_event.json)}      
    lambdaHashingVersion: 20201221
    maximumRetryAttempts: 1
    memorySize: 512    
    name: ${self:custom.env}-${self:custom.service}
    role: !GetAtt LambdaRole.Arn
    runtime: go1.x  
    handler: bin/cmd

resources:
  Resources:
    LambdaRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:custom.env}-${self:custom.service}-lambda-role
        Description: The role for ${self:custom.env}-${self:custom.service}-lambda
        AssumeRolePolicyDocument: ${file(./serverless_configs/policies/trust_policies/lambda_policy.json)}
        # インラインポリシー
        Policies:
          - PolicyName: ${self:custom.env}-${self:custom.service}-lambda-execution-policy
            PolicyDocument: ${file(./serverless_configs/policies/custom_managed_policies/lambda_execution_policy.json)}
        # 管理ポリシー
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AWSLambdaExecute    
          
