# 変数
custom:
  service: notify-slack-of-amplify-events

# サービス名
service: ${self:custom.service}

frameworkVersion: '2'

# プロバイダー
provider:
  name: aws
  region: ap-northeast-1
  stackName: ${env:APP_ENV}-${self:custom.service}-stack
  stage: ${env:APP_ENV}

# デプロイ対象のパッケージ
package:
  patterns:
    - ./bin/**

# Lambda
functions:
  main:
    description: The function that notify slack of amplify events
    events:
      - eventBridge:
          pattern: ${file(./serverless_configs/events/amplify_event.json)}
    image: baseImage
    lambdaHashingVersion: 20201221
    maximumRetryAttempts: 1
    memorySize: 512
    name: ${env:APP_ENV}-${self:custom.service}
    role: !GetAtt LambdaRole.Arn
    runtime: go1.x

# ECR
ecr:
  scanOnPush: true
  images:
    baseImage:
      uri: ${env:AWS_ECR_ACCOUNT_URL}/${env:APP_ENV}-${self:custom.service}-repository@${env:CIRCLE_SHA1}

# 追加AWSリソース
resources:
  Resources:
    LambdaRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${env:APP_ENV}-${self:custom.service}-lambda-role
        Description: The role for ${env:APP_ENV}-${self:custom.service}-lambda
        AssumeRolePolicyDocument: ${file(./serverless_configs/policies/trust_policies/lambda_policy.json)}
        # インラインポリシー
        Policies:
          - PolicyName: ${env:APP_ENV}-${self:custom.service}-lambda-execution-policy
            PolicyDocument: ${file(./serverless_configs/policies/custom_managed_policies/lambda_execution_policy.json)}
        # 管理ポリシー
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AWSLambdaExecute    
          
