version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.0
  aws-ecr: circleci/aws-ecr@7.0.0
  serverless: circleci/serverless-framework@1.0.1
  slack: circleci/slack@4.3.1

commands:

  # 環境変数を準備します．
  setup_env:
    steps:
      - run:
          name: Copy env file
          command: |
            cp .env.docker.example .env.docker
      - run:
          # CircleCIコンテナに出力された環境変数をDockerコンテナで使用できるようにします．
          name: Make env file
          command: |
            echo "APP_ENV=$APP_ENV" > .env.app
            echo "AWS_REGION=$AWS_REGION" >> .env.app
            echo "SLACK_API_TOKEN=$SLACK_API_TOKEN" >> .env.app
            echo "SLACK_CHANNEL_ID=$SLACK_CHANNEL_ID" >> .env.app
      - run:
          name: Make shell file to export env
          command: |
            source ./ops/make_aws_envs.sh

  # go.sumファイルを復元します．
  restore_modules:
    steps:
      - restore_cache:
          keys:
            - go-modules-{{ checksum "go.sum" }}
            - go-modules-

  # 最新のgo.sumを保存します．
  save_modules:
    steps:
      - save_cache:
          key: go-modules-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod

  # 失敗をSlackに通知します．
  notify_of_failure:
    steps:
      - slack/notify:
          template: basic_fail_1
          event: fail

jobs:
  build_and_test:
    machine:
      image: ubuntu-1604:201903-01
    parameters:
      env:
        type: enum
        enum: [ "stg", "prd" ]
    environment:
      APP_ENV: << parameters.env >>
    steps:
      - checkout
      - setup_env
      - run:
          name: Docker compose config
          command: |
            docker-compose config
      - run:
          name: Docker compose run & Go env
          command: |
            set -xe
            docker-compose run -d --rm notify-slack-of-amplify-events
            docker-compose run --rm notify-slack-of-amplify-events go env
      - restore_modules
      - run:
          name: Go mod download
          command: |
            docker-compose run --rm notify-slack-of-amplify-events go mod download -x
      - save_modules
      - run:
          name: Go fmt
          command: |
            docker-compose run --rm  notify-slack-of-amplify-events go fmt ./... >&2
      - run:
          name: Go vet
          command: |
            docker-compose run --rm  notify-slack-of-amplify-events go vet ./...
      - run:
          name: Go test 
          command: |
            docker-compose run --rm notify-slack-of-amplify-events go test -v -cover ./test/unit/...
      - run:
          name: Docker save image
          command: |
            docker save -o . notify-slack-of-amplify-events
      - persist_to_workspace: 
          root: .
          paths:
            - .

  deploy:
    executor: serverless/default
    steps:
      - attach_workspace: 
          at: .
      - run:
          name: Docker load image
          command: |
            docker load -i .
      - run:
          name: Export AWS env values
          command: |
            source aws_envs.sh >> $BASH_ENV
      - aws-ecr/push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          repo: AWS_ECR_REPOSITORY_NAME
          tag: ${CIRCLE_SHA1}            
      - serverless/setup
      - run:
          name: Serverless deploy
          command: |
            serverless deploy -v

workflows:

  develop:
    jobs:
      - build_and_test:
          name: build_and_test_stg
          env: stg
          filters:
            branches:
              only: develop
      - deploy:
          name: deploy_stg
          requires:
            - build_and_test_stg

  main:
    jobs:
      - build_and_test:
          name: build_and_test_prd
          env: prd
          post-steps:
            - notify_of_failure
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /release\/.*/
      - deploy:
          name: deploy_prd
          requires:
            - build_and_test_prd
          post-steps:
            - notify_of_failure
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /release\/.*/ 
