version: 2.1

orbs:
  slack: circleci/slack@4.3.1

commands:
  # 失敗をSlackに通知します．
  notify_of_failure:
    steps:
      - slack/notify:
          template: basic_fail_1
          event: fail

jobs:
  build_and_test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Copy env file
          command: |
            cp .env.example .env
            cp .docker.env.example .docker.env
      - run:
          name: Install Lambda RIE # https://docs.aws.amazon.com/ja_jp/lambda/latest/dg/go-image.html#go-image-other
          command: |
            mkdir -p ~/.aws-lambda-rie
            curl -Lo ~/.aws-lambda-rie/aws-lambda-rie https://github.com/aws/aws-lambda-runtime-interface-emulator/releases/latest/download/aws-lambda-rie
            chmod +x ~/.aws-lambda-rie/aws-lambda-rie
      - run:
          name: Validate docker-compose.yml
          command: |
            docker-compose config
      - run:
          name: Build image & Create container
          command: |
            set -xe
            docker-compose up --build -d
            docker-compose run --rm  notify-slack-of-amplify-events go env
      - run:
          name: Go mod download
          command: |
            docker-compose run --rm notify-slack-of-amplify-events go mod download -x
      - run:
          name: Go fmt
          command: |
            docker-compose run --rm  notify-slack-of-amplify-events go fmt ./... >&2
      - run:
          name: Go vet
          command: |
            docker-compose run --rm  notify-slack-of-amplify-events go vet ./...
#      - run:
#          name: Go test
#          command: |
#           docker-compose run --rm notify-slack-of-amplify-events go test -v -cover ./test/...

workflows:

  develop:
    jobs:
      - build_and_test:
          name: build_and_test_dev
          filters:
            branches:
              only: develop

  main:
    jobs:
      - build_and_test:
          name: build_and_test_prd
          post-steps:
            - notify_of_failure
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /release\/.*/
