version: 2.1

orbs:
  slack: circleci/slack@4.3.1

commands:
  # 失敗をSlackに通知します．
  notify_of_failure:
    steps:
      - slack/notify:
          template: basic_fail_1
          event: fail

jobs:
  build_and_test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Docker compose up
          command: |
            set -xe
            docker-compose up -d
      - run:
          name: Go mod download
          command: |
            docker run -it notify-slack-of-amplify-events go mod download -x
      - run:
          name: Go fmt
          command: |
            docker run -it notify-slack-of-amplify-events go fmt ./... >&2
      - run:
          name: Go vet
          command: |
            docker run -it notify-slack-of-amplify-events go vet ./...
#      - run:
#          name: Go test
#          command: |
#           docker exec -it notify-slack-of-amplify-events go test -v -cover ./...

workflows:

  develop:
    jobs:
      - build_and_test:
          name: build_and_test_stg
          filters:
            branches:
              only: develop

  main:
    jobs:
      - build_and_test:
          name: build_and_test_prd
          post-steps:
            - notify_of_failure
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /release\/.*/
