version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.2
  serverless: circleci/serverless-framework@1.0.1
  slack: circleci/slack@4.3.1

executors:
  primary_container:
    machine:
      image: ubuntu-1604:201903-01

commands:
  # 環境変数を準備します．
  setup_envs:
    steps:
      - run:
          name: Copy env file
          command: |
            cp .env.docker.example .env.docker
      - run:
          # CircleCIコンテナに出力された環境変数をDockerコンテナで使用できるようにします．
          name: Make env file
          command: |
            echo "APP_ENV=$APP_ENV" >> .env
            echo "$AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION" >> .env
            echo "SLACK_API_TOKEN=$SLACK_API_TOKEN" >> .env
            echo "SLACK_CHANNEL_ID=$SLACK_CHANNEL_ID" >> .env
      - run:
          name: Make shell file for env values
          command: |
            printenv | sort -f
            source ./ops/setup_envs.sh

  # go.sumファイルを復元します．
  restore_modules:
    steps:
      - restore_cache:
          keys:
            - go-modules-{{ checksum "go.sum" }}
            - go-modules-

  # 最新のgo.sumを保存します．
  save_modules:
    steps:
      - save_cache:
          key: go-modules-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod

  # 出力する環境変数を用意します．
  export_envs:
    steps:
      - run:
          name: Export envs
          command: |
            source export_envs.sh >> $BASH_ENV
  
  # 環境変数からcredentialsファイルを用意します．
  aws_configure:
    steps:
      - run:
          name: Setup credentials
          command:
            source ./ops/setup_credentials.sh

  # 失敗をSlackに通知します．
  notify_of_failure:
    steps:
      - slack/notify:
          template: basic_fail_1
          event: fail

jobs:
  # ビルドとテストを実行します．
  build_and_test:
    executor: primary_container
    parameters:
      env:
        type: enum
        enum: [ "stg", "prd" ]
    environment:
      APP_ENV: << parameters.env >>
    steps:
      - checkout
      - setup_envs
      - run:
          name: Docker compose config
          command: |
            docker-compose config
      - run:
          name: Docker compose run & Go env
          command: |
            set -xe
            docker-compose run -d --rm notify-slack-of-amplify-events
            docker-compose run --rm notify-slack-of-amplify-events go env
      - restore_modules
      - run:
          name: Go mod download
          command: |
            docker-compose run --rm notify-slack-of-amplify-events go mod download -x
      - save_modules
      - run:
          name: Go fmt
          command: |
            docker-compose run --rm notify-slack-of-amplify-events go fmt ./... >&2
      - run:
          name: Go vet
          command: |
            docker-compose run --rm notify-slack-of-amplify-events go vet ./...
      - run:
          name: Go test
          command: |
            docker-compose run --rm notify-slack-of-amplify-events go test -v -cover ./test/unit/...
      - run:
          name: Docker save image
          command: |
            docker save notify-slack-of-amplify-events > image.tar.gz
            ls -la
      - persist_to_workspace:
          root: .
          paths:
            - .

  # ECRにイメージをプッシュします．
  push_image:
    executor:
      name: aws-cli/default
      python-version: "3.9-node"
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: Docker load image
          command: |
            ls -la
            docker load < image.tar.gz
      - export_envs
      - aws-cli/install
      - aws_configure
      - run:
          name: Docker login
          command: |
            aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${AWS_ECR_ACCOUNT_URL}
      - run:
          name: Docker tag
          command: |
            docker tag notify-slack-of-amplify-events-repository:latest ${AWS_ECR_ACCOUNT_URL}/{$APP_ENV}-notify-slack-of-amplify-events-repository:${CIRCLE_SHA1}
      - run:
          name: Docker push
          command: |
            docker push ${AWS_ECR_ACCOUNT_URL}/{$APP_ENV}-notify-slack-of-amplify-events-repository:${CIRCLE_SHA1}

  # サーバレスアプリケーションをデプロイします．
  deploy:
    executor: serverless/default
    steps:
      - attach_workspace:
          at: .
      - export_envs
      - serverless/setup
      - run:
          name: Serverless deploy
          command: |
            serverless deploy -v

workflows:
  # deveplopブランチフロー
  develop:
    jobs:
      - build_and_test:
          name: build_and_test_stg
          env: stg
          filters:
            branches:
              only: develop
      - push_image:
          name: push_image_stg
          requires:
            - build_and_test_stg
      - deploy:
          name: deploy_stg
          requires:
            - push_image_stg
  # mainブランチフロー
  main:
    jobs:
      - build_and_test:
          name: build_and_test_prd
          env: prd
          post-steps:
            - notify_of_failure
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /release\/.*/
      - push_image:
          name: push_image_prd
          post-steps:
            - notify_of_failure
          requires:
            - build_and_test_prd
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /release\/.*/
      - deploy:
          name: deploy_prd
          post-steps:
            - notify_of_failure
          requires:
            - push_image_prd
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /release\/.*/ 
